version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: redis
    ports:
      - '6380:6379'
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=healthapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backend/database.sql:/docker-entrypoint-initdb.d/database.sql
  backend:
    build:
      context: backend
    ports:
      - "4000:4000"
    environment:
      - COOKIE_SECRET=mysecret
      - DATABASE_NAME=healthapp
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6380
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    depends_on:
      - db
      - redis
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:4000
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    depends_on:
      - backend